# Base Image

FROM dhub.kubesre.xyz/node:18.17.1

WORKDIR /app

# Run yarn only if package.json changes
COPY ./package.json ./
RUN yarn add core-js
RUN node -v
RUN npm -v
RUN yarn install

#COPY . .

EXPOSE 3300

CMD ["yarn", "watch-dev" ]
